Assignment:	 
		g++ model.cpp -c -std=c++0x
		g++ controller.cpp -c
		g++ view.cpp -c
		g++ FastTrackball.c -c
		g++ FastTrackball.o controller.o view.o model.o Main.cpp -o  assignment2 -lglut -lGLU -lGL -std=c++0x

run:
		./assignment2 ../bin/galleon.ply
clear:
		rm -f assignment2
		rm *.o
